version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6335:6333" # You already did this correctly
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
